# Generated by Django 3.2.11 on 2022-01-10 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('move_type', models.PositiveSmallIntegerField(choices=[(1, 'normal'), (2, 'fighting'), (3, 'flying'), (4, 'poison'), (5, 'ground'), (6, 'rock'), (7, 'bug'), (8, 'ghost'), (9, 'steel'), (10, 'fire'), (11, 'water'), (12, 'grass'), (13, 'electric'), (14, 'psychic'), (15, 'ice'), (16, 'dragon'), (17, 'dark'), (18, 'fairy'), (10001, 'unknown'), (10002, 'shadow')])),
                ('target', models.PositiveSmallIntegerField(choices=[(1, 'specific-move'), (2, 'selected-pokemon-me-first'), (3, 'ally'), (4, 'users-field'), (5, 'user-or-ally'), (6, 'opponents-field'), (7, 'user'), (8, 'random-opponent'), (9, 'all-other-pokemon'), (10, 'selected-pokemon'), (11, 'all-opponents'), (12, 'entire-field'), (13, 'user-and-allies'), (14, 'all-pokemon'), (15, 'all-allies')])),
                ('damage_class', models.PositiveSmallIntegerField(choices=[(1, 'status'), (2, 'physical'), (3, 'special')])),
                ('description', models.CharField(max_length=512)),
                ('short_description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('gen_intruduced', models.PositiveSmallIntegerField(choices=[(1, 'generation-i'), (2, 'generation-ii'), (3, 'generation-iii'), (4, 'generation-iv'), (5, 'generation-v'), (6, 'generation-vi'), (7, 'generation-vii'), (8, 'generation-viii')])),
                ('type_1', models.PositiveSmallIntegerField(choices=[(1, 'normal'), (2, 'fighting'), (3, 'flying'), (4, 'poison'), (5, 'ground'), (6, 'rock'), (7, 'bug'), (8, 'ghost'), (9, 'steel'), (10, 'fire'), (11, 'water'), (12, 'grass'), (13, 'electric'), (14, 'psychic'), (15, 'ice'), (16, 'dragon'), (17, 'dark'), (18, 'fairy'), (10001, 'unknown'), (10002, 'shadow')])),
                ('type_2', models.PositiveSmallIntegerField(choices=[(1, 'normal'), (2, 'fighting'), (3, 'flying'), (4, 'poison'), (5, 'ground'), (6, 'rock'), (7, 'bug'), (8, 'ghost'), (9, 'steel'), (10, 'fire'), (11, 'water'), (12, 'grass'), (13, 'electric'), (14, 'psychic'), (15, 'ice'), (16, 'dragon'), (17, 'dark'), (18, 'fairy'), (10001, 'unknown'), (10002, 'shadow')])),
            ],
        ),
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbase.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbase.pokemon')),
            ],
            options={
                'unique_together': {('pokemon', 'move')},
            },
        ),
    ]
