# Generated by Django 3.2.11 on 2022-01-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type_2',
            field=models.PositiveSmallIntegerField(choices=[(1, 'normal'), (2, 'fighting'), (3, 'flying'), (4, 'poison'), (5, 'ground'), (6, 'rock'), (7, 'bug'), (8, 'ghost'), (9, 'steel'), (10, 'fire'), (11, 'water'), (12, 'grass'), (13, 'electric'), (14, 'psychic'), (15, 'ice'), (16, 'dragon'), (17, 'dark'), (18, 'fairy'), (10001, 'unknown'), (10002, 'shadow')], null=True),
        ),
    ]
