# Generated by Django 3.2.11 on 2022-01-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0002_alter_pokemon_type_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
