# Generated by Django 3.2.11 on 2022-01-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0004_auto_20220113_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='accuracy',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='power',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='pp',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='priority',
            field=models.SmallIntegerField(null=True),
        ),
    ]
