# Generated by Django 3.2.11 on 2022-01-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0005_auto_20220113_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='pokemonmove',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='kbase.move'),
        ),
    ]
