# Generated by Django 3.2.11 on 2022-01-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0007_alter_move_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='short_description',
            field=models.CharField(max_length=256),
        ),
    ]
